'use client';

import type { OosReportFormData, OosReportPreviewRow } from '@/lib/oos-reports-records';
import type { OosDashboardMetrics } from '@/lib/oos-types';

interface OosAggregateReportPdfProps {
  reportNumber: string;
  reportType: string;
  filters: OosReportFormData;
  previewRows: OosReportPreviewRow[];
  metrics: OosDashboardMetrics;
  summary: string;
  investigationSummary: string;
  capaSummary: string;
  generatedBy: string;
  generatedDate: string;
}

export function OosAggregateReportPdf({
  reportNumber,
  reportType,
  filters,
  previewRows,
  metrics,
  summary,
  investigationSummary,
  capaSummary,
  generatedBy,
  generatedDate,
}: OosAggregateReportPdfProps) {
  const fmt = (d?: string) => d ? new Date(d).toLocaleDateString('en-GB') : '—';
  const filterLine = [
    `Period: ${fmt(filters.review_period_from)} — ${fmt(filters.review_period_to)}`,
    `Department: ${filters.department || 'All'}`,
    `Product: ${filters.product || 'All'}`,
    `Batch: ${filters.batch_number || 'All'}`,
    `Test: ${filters.test_name || 'All'}`,
    `Status: ${filters.status || 'All'}`,
    `Root Cause: ${filters.root_cause_category || 'All'}`,
  ].join(' | ');

  return (
    <article id="oos-aggregate-report-pdf" className="bg-white text-black p-8 max-w-[210mm] mx-auto text-[11px] leading-relaxed print:p-6">
      <header className="border-2 border-black mb-4">
        <div className="grid grid-cols-3 border-b border-black">
          <div className="p-3 border-r border-black text-center font-bold text-blue-800 text-sm">
            SKYMAP<br />PHARMACEUTICALS PVT. LTD.
          </div>
          <div className="p-3 border-r border-black text-center">
            <p className="font-bold text-sm uppercase">GMP OOS Report</p>
            <p className="text-[10px] mt-1">21 CFR Part 11 | Quality Management System</p>
          </div>
          <div className="p-3 text-[10px] space-y-1">
            <p><strong>Report No.:</strong> {reportNumber}</p>
            <p><strong>Generated:</strong> {fmt(generatedDate)}</p>
            <p><strong>Generated By:</strong> {generatedBy}</p>
            <p><strong>Page:</strong> 1 of 1</p>
          </div>
        </div>
        <div className="p-4 text-center bg-slate-50">
          <h1 className="text-lg font-bold uppercase">{reportType}</h1>
        </div>
      </header>

      <section className="mb-4">
        <h2 className="font-bold text-xs uppercase bg-slate-200 px-2 py-1 border border-black mb-2">Filter Criteria</h2>
        <p className="border border-black p-2 text-[10px]">{filterLine}</p>
      </section>

      <section className="mb-4">
        <h2 className="font-bold text-xs uppercase bg-slate-200 px-2 py-1 border border-black mb-2">Executive Summary</h2>
        <p className="border border-black p-2 mb-2">{summary}</p>
        <table className="w-full border border-black text-[10px]">
          <tbody>
            {[
              ['Total OOS', metrics.total],
              ['Open', metrics.open],
              ['Closed', metrics.closed],
              ['Overdue', metrics.overdue],
              ['Critical', metrics.critical],
              ['CAPA Linked', metrics.capaLinked],
              ['Avg Closure Days', metrics.avgClosureDays],
            ].map(([label, value]) => (
              <tr key={String(label)}>
                <td className="border border-black p-1.5 w-1/2 font-semibold bg-slate-50">{label}</td>
                <td className="border border-black p-1.5">{value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="mb-4">
        <h2 className="font-bold text-xs uppercase bg-slate-200 px-2 py-1 border border-black mb-2">Investigation Summary</h2>
        <p className="border border-black p-2">{investigationSummary}</p>
      </section>

      <section className="mb-4">
        <h2 className="font-bold text-xs uppercase bg-slate-200 px-2 py-1 border border-black mb-2">CAPA Summary</h2>
        <p className="border border-black p-2">{capaSummary}</p>
      </section>

      <section className="mb-4 break-inside-avoid">
        <h2 className="font-bold text-xs uppercase bg-slate-200 px-2 py-1 border border-black mb-2">OOS Register</h2>
        <table className="w-full border border-black text-[9px]">
          <thead>
            <tr className="bg-slate-100">
              <th className="border border-black p-1">OOS No</th>
              <th className="border border-black p-1">Date</th>
              <th className="border border-black p-1">Product</th>
              <th className="border border-black p-1">Batch</th>
              <th className="border border-black p-1">Test</th>
              <th className="border border-black p-1">Status</th>
              <th className="border border-black p-1">CAPA</th>
            </tr>
          </thead>
          <tbody>
            {previewRows.slice(0, 50).map((row) => (
              <tr key={row.oos_number}>
                <td className="border border-black p-1 font-mono">{row.oos_number}</td>
                <td className="border border-black p-1">{fmt(row.oos_date)}</td>
                <td className="border border-black p-1">{row.product_name}</td>
                <td className="border border-black p-1">{row.batch_number}</td>
                <td className="border border-black p-1">{row.test_name}</td>
                <td className="border border-black p-1">{row.status}</td>
                <td className="border border-black p-1">{row.capa_linked}</td>
              </tr>
            ))}
            {!previewRows.length && (
              <tr><td colSpan={7} className="border border-black p-2 text-center">No records for selected criteria</td></tr>
            )}
          </tbody>
        </table>
        {previewRows.length > 50 && (
          <p className="text-[9px] mt-1 italic">Showing first 50 of {previewRows.length} records.</p>
        )}
      </section>

      <section className="mb-4 border border-dashed border-black p-4 text-center text-muted-foreground">
        <p className="font-semibold text-black">Charts Placeholder</p>
        <p className="text-[10px]">Monthly OOS Trend · Product-wise · Test-wise · Root Cause · Phase-I vs Phase-II · CAPA Linkage · Closure Performance</p>
      </section>

      <footer className="border-t border-black pt-2 text-[9px] flex justify-between">
        <span>Confidential — GMP Quality Record</span>
        <span>{reportNumber} · Page 1 of 1</span>
      </footer>
    </article>
  );
}
