'use client';

import { useState, useEffect } from 'react';
import { Save } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { updatePqrDocument } from '@/lib/pqr-service';
import { useAuth } from '@/contexts/auth-context';
import type { PqrDocument, PqrDataSnapshot } from '@/lib/pqr-types';

interface SummaryFormProps {
  pqrId: string;
  document: PqrDocument;
  snapshot: PqrDataSnapshot | null;
  onSaved: () => void;
}

export function PqrSummaryForm({ pqrId, document, snapshot, onSaved }: SummaryFormProps) {
  const { user, profile } = useAuth();
  const [observations, setObservations] = useState('');
  const [conclusions, setConclusions] = useState('');
  const [recommendations, setRecommendations] = useState('');
  const [compliance, setCompliance] = useState<'satisfactory' | 'needs_improvement' | 'unsatisfactory'>('satisfactory');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    setObservations(document.observations || snapshot?.autoGeneratedNarrative?.observations || '');
    setConclusions(document.conclusions || snapshot?.autoGeneratedNarrative?.conclusions || '');
    setRecommendations(document.recommendations || snapshot?.autoGeneratedNarrative?.recommendations || '');
    setCompliance(document.overall_compliance || 'satisfactory');
  }, [document, snapshot]);

  const handleSave = async () => {
    setSaving(true);
    try {
      await updatePqrDocument(pqrId, { observations, conclusions, recommendations, overall_compliance: compliance }, { id: user?.uid, name: profile?.full_name });
      toast.success('Summary saved');
      onSaved();
    } catch {
      toast.error('Failed to save');
    } finally {
      setSaving(false);
    }
  };

  const locked = document.document_status === 'approved';

  return (
    <div className="space-y-4">
      <Card>
        <CardHeader><CardTitle className="text-base">6.1 Observations</CardTitle></CardHeader>
        <CardContent><Textarea value={observations} onChange={(e) => setObservations(e.target.value)} rows={5} disabled={locked} /></CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle className="text-base">6.2 Conclusions</CardTitle></CardHeader>
        <CardContent><Textarea value={conclusions} onChange={(e) => setConclusions(e.target.value)} rows={5} disabled={locked} /></CardContent>
      </Card>
      <Card>
        <CardHeader><CardTitle className="text-base">6.3 Recommendations</CardTitle></CardHeader>
        <CardContent><Textarea value={recommendations} onChange={(e) => setRecommendations(e.target.value)} rows={5} disabled={locked} /></CardContent>
      </Card>
      <div className="space-y-2 max-w-xs">
        <Label>Overall Compliance</Label>
        <Select value={compliance} onValueChange={(v) => setCompliance(v as typeof compliance)} disabled={locked}>
          <SelectTrigger><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="satisfactory">Satisfactory</SelectItem>
            <SelectItem value="needs_improvement">Needs Improvement</SelectItem>
            <SelectItem value="unsatisfactory">Unsatisfactory</SelectItem>
          </SelectContent>
        </Select>
      </div>
      {!locked && (
        <Button onClick={handleSave} disabled={saving} className="bg-blue-600 gap-2"><Save className="h-4 w-4" />Save Summary</Button>
      )}
    </div>
  );
}
