/**
 * Reusable Firebase CRUD service — production Firestore operations with audit fields.
 */
export {
  createDocument,
  getDocument,
  getDocuments,
  updateDocument,
  deleteDocument,
  queryDocuments,
  documentExists,
  createRecord,
  getRecord,
  getRecords,
  updateRecord,
  deleteRecord,
  recordExists,
  getRecordsPaginated,
  timestampNow,
  isFirebaseConfigured,
  type BaseRecord,
  type DocumentActor,
  type DocumentAuditContext,
  type PaginatedResult,
} from '@/lib/firestore';

/** Standard Firestore collection names for Pharma QMS */
export const FIRESTORE_COLLECTIONS = {
  users: 'users',
  roles: 'roles',
  permissions: 'permissions',
  userPermissions: 'user_permissions',
  departments: 'departments',
  designations: 'designations',
  products: 'products',
  batches: 'batches',
  cpvProducts: 'cpv_products',
  cpvBatches: 'cpv_batches',
  cppResults: 'cpp_results',
  cqaResults: 'cqa_results',
  pqrRecords: 'pqr_records',
  deviations: 'deviations',
  oosRecords: 'oos_records',
  capaRecords: 'capa_records',
  changeControls: 'change_controls',
  complaints: 'complaints',
  recalls: 'recalls',
  riskAssessments: 'risk_assessments',
  trainingRecords: 'training_records',
  auditTrail: 'audit_trail',
  notifications: 'notifications',
  profiles: 'profiles',
} as const;
