export {
  fetchPqrOptions,
  fetchEquipmentReviewRecords,
  pullEquipmentData,
  createEquipmentReviewRecord,
  updateEquipmentReviewRecord,
  softDeleteEquipmentReviewRecord,
  saveEquipmentSectionToPqr,
  getEquipmentReviewNarrative,
  recalculateAllEquipmentCompliance,
  logEquipmentReviewView,
  logEquipmentReviewExport,
  logEquipmentNarrativeEdit,
  type PqrEquipmentReviewActor,
} from '@/lib/pqr-equipment-review-service';
