/** Human-readable breadcrumb labels for pharma modules */
export const BREADCRUMB_LABELS: Record<string, string> = {
  dashboard: 'Dashboard',
  admin: 'Administration',
  cpv: 'Continued Process Verification',
  pqr: 'Product Quality Review',
  qms: 'Quality Management System',
  deviation: 'Deviation Management',
  oos: 'OOS Management',
  capa: 'CAPA Management',
  'change-control': 'Change Control',
  stability: 'Stability Management',
  complaints: 'Complaint Management',
  recall: 'Product Recall',
  dms: 'Document Management',
  training: 'Training Management',
  audit: 'Audit Management',
  vendors: 'Vendor Management',
  validation: 'Validation Management',
  csv: 'CSV Management',
  equipment: 'Equipment Management',
  monitoring: 'Environmental Monitoring',
  warehouse: 'Warehouse Management',
  ebmr: 'eBMR',
  batches: 'Batch Registration',
  products: 'Product Master',
  cpp: 'CPP Monitoring',
  cqa: 'CQA Monitoring',
  'raw-materials': 'Raw Material Monitoring',
  'raw-material-monitoring': 'Raw Material Monitoring',
  'packing-materials': 'Packing Material Monitoring',
  'packing-material-monitoring': 'Packing Material Monitoring',
  utility: 'Utility Monitoring',
  'utility-monitoring': 'Utility Monitoring',
  environmental: 'Environmental Monitoring',
  'environmental-monitoring': 'Environmental Monitoring',
  yield: 'Yield Monitoring',
  'yield-monitoring': 'Yield Monitoring',
  'stability-monitoring': 'Stability Monitoring',
  'hold-time': 'Hold Time Monitoring',
  'hold-time-monitoring': 'Hold Time Monitoring',
  'process-capability': 'Process Capability',
  'trend-analysis': 'Trend Analysis',
  'control-charts': 'Control Charts',
  'statistical-process-control': 'Statistical Process Control',
  'risk-assessment': 'Risk Assessment',
  'annual-review': 'Annual CPV Review',
  'ai-analytics': 'AI Analytics',
  'predictive-analytics': 'AI Analytics',
  configuration: 'CPV Configuration',
  settings: 'CPV Configuration',
  'reports-analytics': 'Reports & Analytics',
  reports: 'Reports & Analytics',
  'alert-engine': 'Alert Engine',
  alerts: 'Alert Engine',
  master: 'Master Data',
  materials: 'Material Master',
  abbreviations: 'Abbreviations',
  notifications: 'Notifications',
  profile: 'Profile',
};

export function formatBreadcrumbLabel(segment: string): string {
  return BREADCRUMB_LABELS[segment] ?? segment.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}
