import { z } from 'zod';
import type { RiskLevel } from '@/lib/cpv';

export const RISK_ASSESSMENT_COLLECTION = 'risk_assessment';
export const RISK_CONTROLS_COLLECTION = 'risk_controls';
export const RISK_REVIEWS_COLLECTION = 'risk_reviews';
export const RISK_ASSESSMENT_LEGACY = ['cpv_risk_assessment'] as const;
export const RISK_ASSESSMENT_MODULE = 'CPV Risk Assessment Worksheet';

export const RISK_CATEGORIES = [
  'CPP Risk',
  'CQA Risk',
  'Yield Risk',
  'Stability Risk',
  'Raw Material Risk',
  'Packing Material Risk',
  'Utility Risk',
  'Environmental Risk',
  'Hold Time Risk',
  'Process Capability Risk',
  'Vendor Risk',
  'Equipment Risk',
  'Process Risk',
  'Regulatory Risk',
] as const;

export const RISK_SOURCES = [
  'Manual Assessment',
  'CPP Monitoring',
  'CQA Monitoring',
  'Yield Monitoring',
  'Stability Monitoring',
  'Raw Material Monitoring',
  'Packing Material Monitoring',
  'Utility Monitoring',
  'Environmental Monitoring',
  'Hold Time Monitoring',
  'Trend Analysis',
  'SPC',
  'Process Capability',
  'Deviation',
  'OOS',
  'CAPA',
] as const;

export const PARAMETER_TYPES = [
  'CPP',
  'CQA',
  'Yield',
  'Stability',
  'Raw Material',
  'Packing Material',
  'Utility',
  'Environmental',
  'Hold Time',
  'Process Capability',
] as const;

export const RISK_STATUSES = [
  'Open',
  'Under Review',
  'Mitigation In Progress',
  'Effectiveness Check Pending',
  'Closed',
  'Accepted',
  'Rejected',
] as const;

export const WORKFLOW_STATUSES = [
  'Draft',
  'Review',
  'Approval',
  'Mitigation',
  'Effectiveness Check',
  'Closure',
] as const;

export const EFFECTIVENESS_STATUSES = [
  'Pending',
  'Effective',
  'Partially Effective',
  'Not Effective',
] as const;

export const RISK_LEVELS = ['Low', 'Medium', 'High', 'Critical'] as const;

const requiredText = z.string().trim().min(1, 'Required');

export const riskAssessmentFormSchema = z.object({
  cpvProductId: z.string().trim().optional().default(''),
  productName: requiredText,
  productCode: z.string().trim().optional().default(''),
  batchNumber: z.string().trim().optional().default(''),
  riskCategory: z.enum(RISK_CATEGORIES).default('Process Risk'),
  riskSource: z.enum(RISK_SOURCES).default('Manual Assessment'),
  processStage: z.string().trim().optional().default(''),
  parameterType: z.enum(PARAMETER_TYPES).optional().default('CPP'),
  parameterName: z.string().trim().optional().default(''),
  riskDescription: requiredText,
  potentialImpact: z.string().trim().optional().default(''),
  potentialCause: z.string().trim().optional().default(''),
  existingControls: z.string().trim().optional().default(''),
  severityScore: z.coerce.number().int().min(1).max(10),
  occurrenceScore: z.coerce.number().int().min(1).max(10),
  detectionScore: z.coerce.number().int().min(1).max(10),
  riskOwner: requiredText,
  mitigationAction: z.string().trim().optional().default(''),
  targetCompletionDate: requiredText,
  effectivenessCheckRequired: z.boolean().default(true),
  linkedCapaNumber: z.string().trim().optional().default(''),
  linkedDeviationNumber: z.string().trim().optional().default(''),
  linkedOosNumber: z.string().trim().optional().default(''),
  linkedChangeControlNumber: z.string().trim().optional().default(''),
  remarks: z.string().trim().optional().default(''),
});

export type RiskAssessmentFormData = z.infer<typeof riskAssessmentFormSchema>;

export interface RiskControlRecord {
  controlId: string;
  controlDescription: string;
  controlType: string;
  owner: string;
  targetDate: string;
  status: string;
  effectiveness: string;
}

export interface RiskReviewRecord {
  reviewDate: string;
  reviewer: string;
  comments: string;
  decision: string;
  status: string;
}

export interface RiskAssessmentRecord extends RiskAssessmentFormData, Record<string, unknown> {
  id: string;
  riskAssessmentId: string;
  riskNumber: string;
  rpnScore: number;
  riskLevel: RiskLevel;
  riskStatus: typeof RISK_STATUSES[number];
  workflowStatus: typeof WORKFLOW_STATUSES[number];
  effectivenessStatus: typeof EFFECTIVENESS_STATUSES[number];
  capaSuggested: boolean;
  isAutoGenerated: boolean;
  isLocked: boolean;
  reviewedBy: string;
  reviewDate: string;
  approvedBy: string;
  approvalDate: string;
  controls: RiskControlRecord[];
  reviews: RiskReviewRecord[];
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
  createdByName?: string;
  updatedByName?: string;
  isDeleted: boolean;
}

export interface RiskAssessmentSummary {
  total: number;
  open: number;
  closed: number;
  critical: number;
  high: number;
  medium: number;
  low: number;
  capaLinked: number;
  overdue: number;
}

function round(n: number) {
  return Number.isFinite(n) ? Math.round(n * 1000) / 1000 : 0;
}

export function generateRiskNumber(existingCount: number): string {
  const year = new Date().getFullYear();
  return `RISK/${year}/${String(existingCount + 1).padStart(4, '0')}`;
}

export function buildRiskAssessmentId(productCode: string): string {
  const year = new Date().getFullYear();
  return `RA-${productCode || 'PRD'}-${year}`.replace(/\s+/g, '-').toUpperCase().slice(0, 80);
}

export function calculateRiskAssessment(
  severity: number,
  occurrence: number,
  detection: number,
): { rpnScore: number; riskLevel: RiskLevel } {
  const s = Math.min(10, Math.max(1, severity));
  const o = Math.min(10, Math.max(1, occurrence));
  const d = Math.min(10, Math.max(1, detection));
  const rpnScore = s * o * d;
  let riskLevel: RiskLevel = 'Low';
  if (rpnScore >= 201) riskLevel = 'Critical';
  else if (rpnScore >= 101) riskLevel = 'High';
  else if (rpnScore >= 51) riskLevel = 'Medium';
  return { rpnScore, riskLevel };
}

export function severityBand(score: number): RiskLevel {
  if (score >= 9) return 'Critical';
  if (score >= 7) return 'High';
  if (score >= 4) return 'Medium';
  return 'Low';
}

export function matrixSeverity(score: number): number {
  return Math.min(5, Math.max(1, Math.ceil(score / 2)));
}

export function matrixOccurrence(score: number): number {
  return Math.min(5, Math.max(1, Math.ceil(score / 2)));
}

export function matrixCellLevel(severity: number, occurrence: number): RiskLevel {
  const rpn = severity * occurrence * 5;
  if (rpn >= 60) return 'Critical';
  if (rpn >= 35) return 'High';
  if (rpn >= 15) return 'Medium';
  return 'Low';
}

export function riskLevelColor(level: RiskLevel): string {
  const map: Record<RiskLevel, string> = {
    Low: '#059669',
    Medium: '#d97706',
    High: '#ea580c',
    Critical: '#dc2626',
  };
  return map[level];
}

export function isOverdue(record: RiskAssessmentRecord): boolean {
  if (!record.targetCompletionDate) return false;
  if (['Closed', 'Accepted', 'Rejected'].includes(record.riskStatus)) return false;
  return new Date(`${record.targetCompletionDate}T23:59:59`) < new Date();
}

export function summarizeRiskAssessments(records: RiskAssessmentRecord[]): RiskAssessmentSummary {
  return {
    total: records.length,
    open: records.filter((r) => !['Closed', 'Accepted', 'Rejected'].includes(r.riskStatus)).length,
    closed: records.filter((r) => ['Closed', 'Accepted'].includes(r.riskStatus)).length,
    critical: records.filter((r) => r.riskLevel === 'Critical').length,
    high: records.filter((r) => r.riskLevel === 'High').length,
    medium: records.filter((r) => r.riskLevel === 'Medium').length,
    low: records.filter((r) => r.riskLevel === 'Low').length,
    capaLinked: records.filter((r) => Boolean(r.linkedCapaNumber)).length,
    overdue: records.filter(isOverdue).length,
  };
}

export interface RiskMatrixCell {
  severity: number;
  occurrence: number;
  count: number;
  maxRpn: number;
  level: RiskLevel;
}

export function buildRiskAssessmentMatrix(records: RiskAssessmentRecord[]): RiskMatrixCell[] {
  const cells: RiskMatrixCell[] = [];
  for (let severity = 5; severity >= 1; severity--) {
    for (let occurrence = 1; occurrence <= 5; occurrence++) {
      const cellRecords = records.filter(
        (r) => matrixSeverity(r.severityScore) === severity
          && matrixOccurrence(r.occurrenceScore) === occurrence,
      );
      const maxRpn = cellRecords.length ? Math.max(...cellRecords.map((r) => r.rpnScore)) : 0;
      cells.push({
        severity,
        occurrence,
        count: cellRecords.length,
        maxRpn,
        level: cellRecords.length
          ? cellRecords.reduce((worst, r) => {
            const order = ['Critical', 'High', 'Medium', 'Low'];
            return order.indexOf(r.riskLevel) < order.indexOf(worst) ? r.riskLevel : worst;
          }, 'Low' as RiskLevel)
          : matrixCellLevel(severity, occurrence),
      });
    }
  }
  return cells;
}

export interface RiskHeatCell extends RiskMatrixCell {
  intensity: number;
}

export function buildRiskAssessmentHeatMap(records: RiskAssessmentRecord[]): RiskHeatCell[] {
  const matrix = buildRiskAssessmentMatrix(records);
  const maxCount = Math.max(1, ...matrix.map((c) => c.count));
  return matrix.map((cell) => ({ ...cell, intensity: cell.count / maxCount }));
}

export function buildRiskAssessmentCharts(records: RiskAssessmentRecord[]) {
  const levelMap = new Map<string, number>();
  records.forEach((r) => levelMap.set(r.riskLevel, (levelMap.get(r.riskLevel) || 0) + 1));
  const levelDistribution = Array.from(levelMap.entries()).map(([level, count]) => ({ level, count }));

  const statusMap = new Map<string, number>();
  records.forEach((r) => statusMap.set(r.riskStatus, (statusMap.get(r.riskStatus) || 0) + 1));
  const statusTrend = Array.from(statusMap.entries()).map(([status, count]) => ({ status, count }));

  const catMap = new Map<string, number>();
  records.forEach((r) => catMap.set(r.riskCategory, (catMap.get(r.riskCategory) || 0) + 1));
  const categoryTrend = Array.from(catMap.entries())
    .map(([category, count]) => ({ category, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  const byMonth = new Map<string, number>();
  records.forEach((r) => {
    const key = (r.createdAt || '').slice(0, 7);
    if (key) byMonth.set(key, (byMonth.get(key) || 0) + 1);
  });
  const monthlyTrend = Array.from(byMonth.entries())
    .map(([month, count]) => ({ month, count }))
    .sort((a, b) => a.month.localeCompare(b.month));

  const topRisks = [...records].sort((a, b) => b.rpnScore - a.rpnScore).slice(0, 10);

  return { levelDistribution, statusTrend, categoryTrend, monthlyTrend, topRisks };
}

export function inferRiskFromSignal(input: {
  riskSource: typeof RISK_SOURCES[number];
  riskCategory: typeof RISK_CATEGORIES[number];
  parameterName?: string;
  description: string;
  severity?: number;
  occurrence?: number;
  detection?: number;
}): Pick<RiskAssessmentFormData, 'riskSource' | 'riskCategory' | 'riskDescription' | 'severityScore' | 'occurrenceScore' | 'detectionScore' | 'potentialImpact'> {
  const param = (input.parameterName || '').toLowerCase();
  let severity = input.severity ?? 5;
  let occurrence = input.occurrence ?? 4;
  let detection = input.detection ?? 5;

  if (param.includes('sterility') || input.description.toLowerCase().includes('sterility')) {
    severity = 10; occurrence = 3; detection = 4;
  } else if (param.includes('endotoxin')) {
    severity = 10; occurrence = 3; detection = 4;
  } else if (input.description.toLowerCase().includes('oos') && param.includes('assay')) {
    severity = 8; occurrence = 5; detection = 4;
  } else if (input.riskCategory === 'Environmental Risk' && input.description.toLowerCase().includes('grade a')) {
    severity = 10; occurrence = 4; detection = 3;
  } else if (input.riskSource === 'Process Capability') {
    severity = input.description.includes('1.0') ? 8 : 6;
  } else if (input.description.toLowerCase().includes('oot')) {
    severity = 6; occurrence = 6;
  }

  return {
    riskSource: input.riskSource,
    riskCategory: input.riskCategory,
    riskDescription: input.description,
    severityScore: severity,
    occurrenceScore: occurrence,
    detectionScore: detection,
    potentialImpact: input.description,
  };
}
