/**
 * Central Firestore collection registry for Pharma QMS + PQR + CPV.
 */

export const AUDIT_FIELDS = [
  'createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'status', 'isDeleted',
] as const;

export const COLLECTION_REGISTRY = {
  // Admin & Auth
  profiles: { module: 'Admin', path: 'profiles' },
  users: { module: 'Admin', path: 'users' },
  roles: { module: 'Admin', path: 'roles' },
  permissions: { module: 'Admin', path: 'permissions' },
  departments: { module: 'Admin', path: 'departments' },
  designations: { module: 'Admin', path: 'designations' },
  company_sites: { module: 'Admin', path: 'company_sites' },
  workflows: { module: 'Admin', path: 'workflows' },
  approval_matrix: { module: 'Admin', path: 'approval_matrix' },
  document_numbering: { module: 'Admin', path: 'document_numbering' },
  notification_settings: { module: 'Admin', path: 'notification_settings' },
  esign_settings: { module: 'Admin', path: 'esign_settings' },
  system_settings: { module: 'Admin', path: 'system_settings' },
  backup_history: { module: 'Admin', path: 'backup_history' },
  backup_restore: { module: 'Admin', path: 'backup_restore' },
  login_activity: { module: 'Admin', path: 'login_activity' },
  access_reviews: { module: 'Admin', path: 'access_reviews' },
  password_policy: { module: 'Admin', path: 'password_policy' },
  module_configuration: { module: 'Admin', path: 'module_configuration' },
  email_sms_templates: { module: 'Admin', path: 'email_sms_templates' },
  master_data_import_export: { module: 'Admin', path: 'master_data_import_export' },

  // Master Data
  products: { module: 'Product', path: 'products' },
  batches: { module: 'Batch', path: 'batches' },
  parameters: { module: 'Product', path: 'parameters' },
  material_master: { module: 'Material', path: 'material_master' },
  vendor_master: { module: 'Vendor', path: 'vendor_master' },
  warehouse_materials: { module: 'Warehouse', path: 'warehouse_materials' },

  // CPV
  cpv_reviews: { module: 'CPV', path: 'cpv_reviews' },
  cpp_parameters: { module: 'CPP', path: 'cpp_parameters' },
  cpp_results: { module: 'CPP', path: 'cpp_results' },
  cqa_parameters: { module: 'CQA', path: 'cqa_parameters' },
  cqa_results: { module: 'CQA', path: 'cqa_results' },
  risk_assessment: { module: 'CPV', path: 'risk_assessment' },
  risk_assessments: { module: 'Risk Management', path: 'risk_assessments' },
  risk_register: { module: 'Risk Management', path: 'risk_register' },
  risk_controls: { module: 'Risk Management', path: 'risk_controls' },
  cpv_cpp: { module: 'CPP', path: 'cpv_cpp', requiredFields: ['productName', 'batchNo', 'parameterName', 'observedValue', 'status'] },
  cpv_cqa: { module: 'CQA', path: 'cpv_cqa', requiredFields: ['productName', 'batchNo', 'testParameter', 'observedValue', 'status'] },
  cpv_yield: { module: 'CPV', path: 'cpv_yield' },
  cpv_utility: { module: 'CPV', path: 'cpv_utility' },
  cpv_batches: { module: 'CPV', path: 'cpv_batches', requiredFields: ['batchNumber', 'productName', 'status'] },
  cpv_raw_materials: { module: 'CPV', path: 'cpv_raw_materials' },
  raw_material_monitoring: { module: 'CPV', path: 'raw_material_monitoring' },
  yield_monitoring: { module: 'CPV', path: 'yield_monitoring' },
  environmental_monitoring: { module: 'CPV', path: 'environmental_monitoring' },
  area_master: { module: 'CPV', path: 'area_master' },
  utility_monitoring: { module: 'CPV', path: 'utility_monitoring' },
  utility_master: { module: 'CPV', path: 'utility_master' },
  packing_material_monitoring: { module: 'CPV', path: 'packing_material_monitoring' },
  cpv_packing_materials: { module: 'CPV', path: 'cpv_packing_materials' },
  packaging_material_master: { module: 'CPV', path: 'packaging_material_master' },
  cpv_environment_monitoring: { module: 'CPV', path: 'cpv_environment_monitoring' },
  cpv_stability_studies: { module: 'CPV', path: 'cpv_stability_studies' },
  stability_schedules: { module: 'CPV', path: 'stability_schedules' },
  stability_results: { module: 'CPV', path: 'stability_results' },
  stability_monitoring: { module: 'CPV', path: 'stability_monitoring' },
  cpv_hold_time: { module: 'CPV', path: 'cpv_hold_time' },
  hold_time_monitoring: { module: 'CPV', path: 'hold_time_monitoring' },
  hold_time_master: { module: 'CPV', path: 'hold_time_master' },
  cpv_capability: { module: 'CPV', path: 'cpv_capability' },
  process_capability: { module: 'CPV', path: 'process_capability' },
  cpv_trends: { module: 'CPV', path: 'cpv_trends' },
  trend_analysis: { module: 'CPV', path: 'trend_analysis' },
  control_charts: { module: 'CPV', path: 'control_charts' },
  spc_rule_violations: { module: 'CPV', path: 'spc_rule_violations' },
  cpv_control_charts: { module: 'CPV', path: 'cpv_control_charts' },
  cpv_risk_assessment: { module: 'CPV', path: 'cpv_risk_assessment' },
  cpv_annual_review: { module: 'CPV', path: 'cpv_annual_review' },
  cpv_alerts: { module: 'CPV', path: 'cpv_alerts' },
  cpv_config_products: { module: 'CPV', path: 'cpv_config_products' },
  cpv_config_cpp_master: { module: 'CPP', path: 'cpv_config_cpp_master' },
  cpv_config_cqa_master: { module: 'CQA', path: 'cpv_config_cqa_master' },
  cpv_config_limit_master: { module: 'CPV', path: 'cpv_config_limit_master' },
  cpv_config_control_limit_master: { module: 'CPV', path: 'cpv_config_control_limit_master' },
  cpv_config_target_master: { module: 'CPV', path: 'cpv_config_target_master' },
  cpv_config_sampling: { module: 'CPV', path: 'cpv_config_sampling' },
  cpv_config_alerts: { module: 'CPV', path: 'cpv_config_alerts' },
  cpv_config_review: { module: 'CPV', path: 'cpv_config_review' },
  cpv_config_workflow: { module: 'CPV', path: 'cpv_config_workflow' },
  cpv_audit_trail: { module: 'CPV', path: 'cpv_audit_trail', auditImmutable: true },

  // QMS
  deviations: { module: 'Deviation', path: 'deviations' },
  oos_records: { module: 'OOS', path: 'oos_records' },
  oos: { module: 'OOS', path: 'oos' },
  capa_records: { module: 'CAPA', path: 'capa_records' },
  capa: { module: 'CAPA', path: 'capa' },
  change_control: { module: 'Change Control', path: 'change_control' },
  change_controls: { module: 'Change Control', path: 'change_controls' },
  change_implementation_plans: { module: 'Change Control', path: 'change_implementation_plans' },
  change_implementation_tasks: { module: 'Change Control', path: 'change_implementation_tasks' },
  change_implementation_actions: { module: 'Change Control', path: 'change_implementation_actions' },
  change_risk_assessments: { module: 'Change Control', path: 'change_risk_assessments' },
  change_impact_assessments: { module: 'Change Control', path: 'change_impact_assessments' },
  change_effectiveness_reviews: { module: 'Change Control', path: 'change_effectiveness_reviews' },
  change_approvals: { module: 'Change Control', path: 'change_approvals' },
  change_approval_history: { module: 'Change Control', path: 'change_approval_history' },
  change_closure: { module: 'Change Control', path: 'change_closure' },
  change_reports: { module: 'Change Control', path: 'change_reports' },
  validation_assessments: { module: 'Change Control', path: 'validation_assessments' },
  csv_assessments: { module: 'Change Control', path: 'csv_assessments' },
  complaints: { module: 'Complaint', path: 'complaints' },
  recall_records: { module: 'Recall', path: 'recall_records' },
  recalls: { module: 'Recall', path: 'recalls' },
  recall_reports: { module: 'Recall', path: 'recall_reports' },
  recall_distribution: { module: 'Recall', path: 'recall_distribution' },
  recall_recovery: { module: 'Recall', path: 'recall_recovery' },
  recall_regulatory_notifications: { module: 'Recall', path: 'recall_regulatory_notifications' },
  recall_closure: { module: 'Recall', path: 'recall_closure' },
  recall_trends: { module: 'Recall', path: 'recall_trends' },
  stability_studies: { module: 'CPV', path: 'stability_studies' },
  stability: { module: 'Stability', path: 'stability' },
  pqr_documents: { module: 'PQR', path: 'pqr_documents' },
  pqr_records: { module: 'PQR', path: 'pqr_records' },
  pqr_batches: { module: 'PQR', path: 'pqr_batches' },
  documents: { module: 'DMS', path: 'documents' },
  dms_documents: { module: 'DMS', path: 'dms_documents' },
  training_records: { module: 'Training', path: 'training_records' },
  training_master: { module: 'Training', path: 'training_master' },
  training_assignments: { module: 'Training', path: 'training_assignments' },
  training_assessments: { module: 'Training', path: 'training_assessments' },
  training_effectiveness: { module: 'Training', path: 'training_effectiveness' },
  training_matrix: { module: 'Training', path: 'training_matrix' },
  training_matrix_compliance: { module: 'Training', path: 'training_matrix_compliance' },
  training_attendance: { module: 'Training', path: 'training_attendance' },
  competency_records: { module: 'Training', path: 'competency_records' },
  document_training_links: { module: 'Training', path: 'document_training_links' },
  training_certificates: { module: 'Training', path: 'training_certificates' },
  trainer_certifications: { module: 'Training', path: 'trainer_certifications' },
  trainer_assessment_checklists: { module: 'Training', path: 'trainer_assessment_checklists' },
  induction_records: { module: 'Training', path: 'induction_records' },
  training_needs_identification: { module: 'Training', path: 'training_needs_identification' },
  job_descriptions: { module: 'Training', path: 'job_descriptions' },
  ojt_training_plans: { module: 'Training', path: 'ojt_training_plans' },
  ojt_competency_matrix: { module: 'Training', path: 'ojt_competency_matrix' },
  self_reading_declarations: { module: 'Training', path: 'self_reading_declarations' },
  annual_training_plans: { module: 'Training', path: 'annual_training_plans' },
  training_requests: { module: 'Training', path: 'training_requests' },
  question_bank: { module: 'Training', path: 'question_bank' },
  questionnaires: { module: 'Training', path: 'questionnaires' },
  questionnaire_attempts: { module: 'Training', path: 'questionnaire_attempts' },
  practical_assessments: { module: 'Training', path: 'practical_assessments' },
  training_settings: { module: 'Training', path: 'training_settings' },
  need_based_training: { module: 'Training', path: 'need_based_training' },
  external_training_records: { module: 'Training', path: 'external_training_records' },
  trainer_qualifications: { module: 'Training', path: 'trainer_qualifications' },
  trainer_renewals: { module: 'Training', path: 'trainer_renewals' },
  training_automation_log: { module: 'Training', path: 'training_automation_log', auditImmutable: true },
  training_planner_items: { module: 'Training', path: 'training_planner_items' },
  lms_connections: { module: 'LMS Integration', path: 'lms_connections' },
  lms_courses: { module: 'LMS Integration', path: 'lms_courses' },
  lms_users: { module: 'LMS Integration', path: 'lms_users' },
  lms_training_records: { module: 'LMS Integration', path: 'lms_training_records' },
  lms_sync_jobs: { module: 'LMS Integration', path: 'lms_sync_jobs' },
  integration_logs: { module: 'LMS Integration', path: 'integration_logs', auditImmutable: true },
  integration_settings: { module: 'LMS Integration', path: 'integration_settings' },
  training_events: { module: 'Training', path: 'training_events' },
  training_schedule: { module: 'Training', path: 'training_schedule' },
  training_rooms: { module: 'Training', path: 'training_rooms' },
  trainers: { module: 'Training', path: 'trainers' },
  retraining_records: { module: 'Training', path: 'retraining_records' },
  training_assignments_sessions: { module: 'Training', path: 'training_assignments_sessions' },
  approval_workflows: { module: 'Training', path: 'approval_workflows' },
  approval_requests: { module: 'Training', path: 'approval_requests' },
  approval_steps: { module: 'Training', path: 'approval_steps' },
  approval_requests_history: { module: 'Training', path: 'approval_requests_history', auditImmutable: true },
  sop_management: { module: 'DMS', path: 'sop_management' },
  sop_master: { module: 'DMS', path: 'sop_master' },
  sop_versions: { module: 'DMS', path: 'sop_versions' },
  sop_reviews: { module: 'DMS', path: 'sop_reviews' },
  sop_approvals: { module: 'DMS', path: 'sop_approvals' },
  sop_training_links: { module: 'DMS', path: 'sop_training_links' },
  sop_distribution: { module: 'DMS', path: 'sop_distribution' },
  sop_acknowledgements: { module: 'DMS', path: 'sop_acknowledgements' },
  sop_periodic_reviews: { module: 'DMS', path: 'sop_periodic_reviews' },
  sop_archive: { module: 'DMS', path: 'sop_archive' },
  work_instructions: { module: 'DMS', path: 'work_instructions' },
  wi_versions: { module: 'DMS', path: 'wi_versions' },
  wi_reviews: { module: 'DMS', path: 'wi_reviews' },
  wi_approvals: { module: 'DMS', path: 'wi_approvals' },
  wi_training_links: { module: 'DMS', path: 'wi_training_links' },
  wi_distribution: { module: 'DMS', path: 'wi_distribution' },
  wi_acknowledgements: { module: 'DMS', path: 'wi_acknowledgements' },
  wi_periodic_reviews: { module: 'DMS', path: 'wi_periodic_reviews' },
  wi_archive: { module: 'DMS', path: 'wi_archive' },
  forms_templates: { module: 'DMS', path: 'forms_templates' },
  form_versions: { module: 'DMS', path: 'form_versions' },
  form_reviews: { module: 'DMS', path: 'form_reviews' },
  form_approvals: { module: 'DMS', path: 'form_approvals' },
  form_distribution: { module: 'DMS', path: 'form_distribution' },
  form_acknowledgements: { module: 'DMS', path: 'form_acknowledgements' },
  form_periodic_reviews: { module: 'DMS', path: 'form_periodic_reviews' },
  form_archive: { module: 'DMS', path: 'form_archive' },
  distribution_lists: { module: 'DMS', path: 'distribution_lists' },
  distribution_groups: { module: 'DMS', path: 'distribution_groups' },
  document_distribution: { module: 'DMS', path: 'document_distribution' },
  document_acknowledgements: { module: 'DMS', path: 'document_acknowledgements' },
  read_confirmations: { module: 'DMS', path: 'read_confirmations' },
  document_versions: { module: 'DMS', path: 'document_versions' },
  document_revisions: { module: 'DMS', path: 'document_revisions' },
  review_workflows: { module: 'DMS', path: 'review_workflows' },
  review_steps: { module: 'DMS', path: 'review_steps' },
  review_comments: { module: 'DMS', path: 'review_comments' },
  review_checklists: { module: 'DMS', path: 'review_checklists' },
  document_approvals: { module: 'DMS', path: 'document_approvals' },
  approval_delegations: { module: 'DMS', path: 'approval_delegations' },
  approval_escalations: { module: 'DMS', path: 'approval_escalations' },
  approval_comments: { module: 'DMS', path: 'approval_comments' },
  document_effective_dates: { module: 'DMS', path: 'document_effective_dates' },
  periodic_reviews: { module: 'DMS', path: 'periodic_reviews' },
  document_archive: { module: 'DMS', path: 'document_archive' },
  archive_jobs: { module: 'DMS', path: 'archive_jobs' },
  archive_policies: { module: 'DMS', path: 'archive_policies' },
  archive_requests: { module: 'DMS', path: 'archive_requests' },
  archive_restoration_requests: { module: 'DMS', path: 'archive_restoration_requests' },
  archive_locations: { module: 'DMS', path: 'archive_locations' },
  retention_policies: { module: 'DMS', path: 'retention_policies' },
  retention_schedules: { module: 'DMS', path: 'retention_schedules' },
  retention_reviews: { module: 'DMS', path: 'retention_reviews' },
  retention_events: { module: 'DMS', path: 'retention_events' },
  disposal_requests: { module: 'DMS', path: 'disposal_requests' },
  disposal_approvals: { module: 'DMS', path: 'disposal_approvals' },
  disposal_certificates: { module: 'DMS', path: 'disposal_certificates' },
  legal_holds: { module: 'DMS', path: 'legal_holds' },
  regulatory_holds: { module: 'DMS', path: 'regulatory_holds' },
  external_documents: { module: 'DMS', path: 'external_documents' },
  external_document_versions: { module: 'DMS', path: 'external_document_versions' },
  external_document_reviews: { module: 'DMS', path: 'external_document_reviews' },
  external_document_distribution: { module: 'DMS', path: 'external_document_distribution' },
  external_document_sources: { module: 'DMS', path: 'external_document_sources' },
  external_document_categories: { module: 'DMS', path: 'external_document_categories' },
  supplier_documents: { module: 'DMS', path: 'supplier_documents' },
  regulatory_documents: { module: 'DMS', path: 'regulatory_documents' },
  standards_documents: { module: 'DMS', path: 'standards_documents' },
  safety_documents: { module: 'DMS', path: 'safety_documents' },
  linked_internal_documents: { module: 'DMS', path: 'linked_internal_documents' },
  print_requests: { module: 'DMS', path: 'print_requests' },
  printed_documents: { module: 'DMS', path: 'printed_documents' },
  print_copies: { module: 'DMS', path: 'print_copies' },
  print_locations: { module: 'DMS', path: 'print_locations' },
  print_distribution: { module: 'DMS', path: 'print_distribution' },
  print_reconciliation: { module: 'DMS', path: 'print_reconciliation' },
  print_returns: { module: 'DMS', path: 'print_returns' },
  print_destruction: { module: 'DMS', path: 'print_destruction' },
  watermark_templates: { module: 'DMS', path: 'watermark_templates' },
  watermark_rules: { module: 'DMS', path: 'watermark_rules' },
  watermark_history: { module: 'DMS', path: 'watermark_history' },
  document_watermarks: { module: 'DMS', path: 'document_watermarks' },
  audit_events: { module: 'DMS', path: 'audit_events', auditImmutable: true },
  audit_exports: { module: 'DMS', path: 'audit_exports' },
  audit_filters: { module: 'DMS', path: 'audit_filters' },
  review_schedules: { module: 'DMS', path: 'review_schedules' },
  review_decisions: { module: 'DMS', path: 'review_decisions' },
  electronic_signatures: { module: 'DMS', path: 'electronic_signatures' },
  signature_meanings: { module: 'DMS', path: 'signature_meanings' },
  signature_sessions: { module: 'DMS', path: 'signature_sessions' },
  signature_settings: { module: 'DMS', path: 'signature_settings' },
  esign_records: { module: 'Admin', path: 'esign_records', auditImmutable: true },
  production_lines: { module: 'DMS', path: 'production_lines' },
  audits: { module: 'Audit', path: 'audits' },
  audit_mgmt_records: { module: 'Audit', path: 'audit_mgmt_records' },
  vendors: { module: 'Vendor', path: 'vendors' },
  vendor_records: { module: 'Vendor', path: 'vendor_records' },
  validation_records: { module: 'Validation', path: 'validation_records' },
  csv_systems: { module: 'CSV', path: 'csv_systems' },
  equipment_master: { module: 'Equipment', path: 'equipment_master' },
  equipment_records: { module: 'Equipment', path: 'equipment_records' },
  calibration_records: { module: 'Equipment', path: 'calibration_records' },
  monitoring_records: { module: 'Monitoring', path: 'monitoring_records' },
  warehouse_records: { module: 'Warehouse', path: 'warehouse_records' },
  ebmr_records: { module: 'eBMR', path: 'ebmr_records' },

  // System
  audit_logs: { module: 'Admin', path: 'audit_logs', auditImmutable: true },
  audit_trail: { module: 'Admin', path: 'audit_trail', auditImmutable: true },
  notifications: { module: 'Admin', path: 'notifications' },
} as const;

export type CollectionName = keyof typeof COLLECTION_REGISTRY;

export function validateRecordMetadata(data: Record<string, unknown>): string[] {
  const errors: string[] = [];
  if (!data.createdAt && !data.created_at) errors.push('Missing createdAt');
  if (!data.updatedAt && !data.updated_at) errors.push('Missing updatedAt');
  return errors;
}

export function validateRequiredFields(
  collection: CollectionName,
  data: Record<string, unknown>,
): string[] {
  const spec = COLLECTION_REGISTRY[collection];
  const required = 'requiredFields' in spec ? spec.requiredFields : undefined;
  if (!required) return [];
  return required.filter((f) => data[f] === undefined || data[f] === null || data[f] === '');
}

export const RECOMMENDED_INDEXES = [
  { collection: 'notifications', fields: ['userId', 'createdAt'] },
  { collection: 'notifications', fields: ['userId', 'isRead'] },
  { collection: 'audit_trail', fields: ['moduleName', 'timestamp'] },
  { collection: 'audit_trail', fields: ['collectionName', 'documentId'] },
  { collection: 'lms_sync_jobs', fields: ['connection_id', 'started_at'] },
  { collection: 'lms_sync_jobs', fields: ['status', 'started_at'] },
  { collection: 'integration_logs', fields: ['connection_id', 'created_at'] },
  { collection: 'lms_courses', fields: ['connection_id', 'imported_at'] },
  { collection: 'lms_users', fields: ['connection_id', 'imported_at'] },
  { collection: 'training_certificates', fields: ['employee_id', 'expiry_date'] },
  { collection: 'training_certificates', fields: ['department', 'certificate_status'] },
  { collection: 'training_certificates', fields: ['created_at'] },
  { collection: 'training_certificates', fields: ['issue_date'] },
  { collection: 'retraining_records', fields: ['created_at'] },
  { collection: 'retraining_records', fields: ['due_date'] },
  { collection: 'retraining_records', fields: ['employee_id', 'due_date'] },
  { collection: 'retraining_records', fields: ['retraining_status', 'due_date'] },
  { collection: 'retraining_records', fields: ['department', 'retraining_status'] },
  { collection: 'retraining_records', fields: ['trigger_type', 'created_at'] },
  { collection: 'training_assignments', fields: ['employee_id', 'created_at'] },
  { collection: 'training_assignments', fields: ['employee_id', 'status'] },
  { collection: 'training_records', fields: ['employee_id', 'created_at'] },
  { collection: 'training_records', fields: ['employee_id', 'training_date'] },
  { collection: 'training_events', fields: ['start_date', 'status'] },
  { collection: 'training_events', fields: ['department', 'start_date'] },
  { collection: 'training_events', fields: ['trainer', 'start_date'] },
  { collection: 'approval_requests', fields: ['module', 'created_at'] },
  { collection: 'approval_requests', fields: ['module', 'current_status', 'created_at'] },
  { collection: 'approval_requests', fields: ['module', 'workflow_type', 'created_at'] },
  { collection: 'approval_steps', fields: ['request_id', 'step_number'] },
  { collection: 'approval_requests_history', fields: ['created_at'] },
  { collection: 'cpv_cpp', fields: ['productName', 'createdAt'] },
  { collection: 'cpv_cqa', fields: ['batchNo', 'createdAt'] },
  { collection: 'cpv_batches', fields: ['status', 'createdAt'] },
  { collection: 'deviations', fields: ['status', 'createdAt'] },
  { collection: 'capa_records', fields: ['status', 'createdAt'] },
  { collection: 'oos_records', fields: ['status', 'createdAt'] },
  { collection: 'pqr_records', fields: ['status', 'createdAt'] },
  { collection: 'profiles', fields: ['role', 'is_active'] },
] as const;
