export const PQR_COLLECTIONS = {
  documents: 'pqr_documents',
  approvals: 'pqr_approvals',
  revisions: 'pqr_revision_history',
  batches: 'pqr_batches',
  snapshots: 'pqr_snapshots',
  products: 'products',
  materialReview: 'material_review',
} as const;

export type PqrDocumentStatus = 'draft' | 'under_review' | 'approved' | 'rejected' | 'archived';

export interface PqrDocument {
  id?: string;
  company_name: string;
  site_name: string;
  address: string;
  document_title: string;
  product_name: string;
  product_id?: string;
  product_code: string;
  pqr_number: string;
  page_number: string;
  revision_number: string;
  format_number: string;
  review_period_from: string;
  review_period_to: string;
  pqr_year: number;
  total_review_months?: number;
  total_batches_manufactured: number;
  total_released_batches: number;
  total_rejected_batches: number;
  total_reworked_batches: number;
  total_reprocessed_batches: number;
  document_status: PqrDocumentStatus;
  review_frequency: string;
  current_revision: string;
  previous_revision: string;
  next_review_due_date: string | null;
  document_owner_department: string;
  effective_date: string | null;
  prepared_date: string | null;
  company_logo_url: string;
  observations: string;
  conclusions: string;
  recommendations: string;
  overall_compliance: 'satisfactory' | 'needs_improvement' | 'unsatisfactory';
  oos_count?: number;
  deviation_count?: number;
  capa_count?: number;
  change_control_count?: number;
  stability_status?: string;
  generic_name?: string;
  strength?: string;
  dosage_form?: string;
  snapshot_id?: string;
  last_refreshed_at?: string;
  created_by?: string;
  created_at?: string;
  updated_at?: string;
}

export interface PqrApproval {
  id?: string;
  pqr_id: string;
  approval_type: 'prepared' | 'reviewed' | 'approved';
  designation: string;
  name: string;
  signature_url: string;
  signature_text: string;
  approval_date: string | null;
  status: 'pending' | 'approved' | 'rejected';
  remarks: string;
  esign_user_id?: string;
  esign_role?: string;
  esign_ip?: string;
  esign_meaning?: string;
  esign_reason?: string;
  created_by?: string;
}

export interface PqrBatchRecord {
  id?: string;
  pqr_id?: string;
  batch_number: string;
  product_name: string;
  manufacturing_date?: string;
  expiry_date?: string;
  batch_size?: string;
  batch_status?: string;
  yield_percentage?: number;
  release_status?: string;
}

export interface PqrSnapshotSection {
  total: number;
  open?: number;
  records: Record<string, unknown>[];
  summary?: string;
}

export interface PqrDataSnapshot {
  id?: string;
  pqr_id: string;
  generatedAt: string;
  product_name: string;
  review_period_from: string;
  review_period_to: string;
  batches: PqrSnapshotSection & {
    manufactured: number;
    released: number;
    rejected: number;
    reworked: number;
    reprocessed: number;
  };
  cpp: PqrSnapshotSection & { complies: number; oot: number; oos: number };
  cqa: PqrSnapshotSection & { complies: number; oot: number; oos: number };
  deviations: PqrSnapshotSection;
  oos: PqrSnapshotSection;
  capa: PqrSnapshotSection;
  changeControl: PqrSnapshotSection;
  stability: PqrSnapshotSection;
  materials: PqrSnapshotSection;
  packaging: PqrSnapshotSection;
  equipment: PqrSnapshotSection;
  trends: {
    monthlyBatches: { month: string; released: number; rejected: number }[];
    oosTrend: { month: string; count: number }[];
    yieldTrend: { month: string; yield: number }[];
  };
  autoGeneratedNarrative?: {
    observations: string;
    conclusions: string;
    recommendations: string;
  };
}

export interface ESignPayload {
  approvalId: string;
  password: string;
  reason: string;
  meaning: 'Prepared By' | 'Reviewed By' | 'Approved By' | 'Rejected By' | 'Verified By';
}
